# Databricks notebook source
# MAGIC %md
# MAGIC # 005 - Gold: Modelo Dimensional (Kimball)
# MAGIC
# MAGIC Este notebook lê as tabelas da camada **Silver** e constrói o modelo dimensional
# MAGIC no schema `workspace.gold`, seguindo a metodologia de **Ralph Kimball**.
# MAGIC
# MAGIC ## Schema Estrela
# MAGIC
# MAGIC ```
# MAGIC               dim_tempo
# MAGIC              (FK_TEMPO)
# MAGIC                   │
# MAGIC                   │
# MAGIC dim_produto ── fato_vendas ── dim_localidade
# MAGIC (FK_PRODUTO)        │           (FK_LOCALIDADE)
# MAGIC                     │
# MAGIC               dim_cliente
# MAGIC              (FK_CLIENTE)
# MAGIC ```

# COMMAND ----------

# MAGIC %md
# MAGIC ## 1. Ler tabelas da Silver

# COMMAND ----------

df_categoria   = spark.read.format("delta").table("silver.categoria")
df_cliente     = spark.read.format("delta").table("silver.cliente")
df_endereco    = spark.read.format("delta").table("silver.endereco")
df_estado      = spark.read.format("delta").table("silver.estado")
df_fornecedor  = spark.read.format("delta").table("silver.fornecedor")
df_item_pedido = spark.read.format("delta").table("silver.item_pedido")
df_municipio   = spark.read.format("delta").table("silver.municipio")
df_pedido      = spark.read.format("delta").table("silver.pedido")
df_produto     = spark.read.format("delta").table("silver.produto")
df_regiao      = spark.read.format("delta").table("silver.regiao")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2. Dimensão: `dim_produto`
# MAGIC
# MAGIC Desnormaliza produto + categoria + fornecedor em uma única dimensão.

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS gold.dim_produto

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE gold.dim_produto (
# MAGIC     SK_PRODUTO         BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC     CODIGO_PRODUTO     INT,
# MAGIC     NOME_PRODUTO       VARCHAR(200),
# MAGIC     NOME_CATEGORIA     VARCHAR(100),
# MAGIC     NOME_FORNECEDOR    VARCHAR(200),
# MAGIC     VALOR_PRECO        DOUBLE
# MAGIC )
# MAGIC USING DELTA;

# COMMAND ----------

df_produto.createOrReplaceTempView("produto")
df_categoria.createOrReplaceTempView("categoria")
df_fornecedor.createOrReplaceTempView("fornecedor")

# COMMAND ----------

# MAGIC %sql
# MAGIC WITH produto_relacional AS (
# MAGIC     SELECT p.codigo_produto,
# MAGIC            p.nome_produto,
# MAGIC            c.nome_categoria,
# MAGIC            f.nome_fornecedor,
# MAGIC            p.valor_preco
# MAGIC       FROM produto p
# MAGIC            INNER JOIN categoria c
# MAGIC              ON p.codigo_categoria = c.codigo_categoria
# MAGIC            INNER JOIN fornecedor f
# MAGIC              ON p.codigo_fornecedor = f.codigo_fornecedor
# MAGIC )
# MAGIC MERGE INTO gold.dim_produto AS d
# MAGIC USING produto_relacional AS r
# MAGIC ON d.codigo_produto = r.codigo_produto
# MAGIC
# MAGIC WHEN MATCHED AND (d.nome_produto <> r.nome_produto OR d.nome_categoria <> r.nome_categoria
# MAGIC                   OR d.nome_fornecedor <> r.nome_fornecedor OR d.valor_preco <> r.valor_preco) THEN
# MAGIC     UPDATE SET nome_produto    = r.nome_produto,
# MAGIC                nome_categoria  = r.nome_categoria,
# MAGIC                nome_fornecedor = r.nome_fornecedor,
# MAGIC                valor_preco     = r.valor_preco
# MAGIC
# MAGIC WHEN NOT MATCHED THEN
# MAGIC     INSERT (codigo_produto, nome_produto, nome_categoria, nome_fornecedor, valor_preco)
# MAGIC     VALUES (r.codigo_produto, r.nome_produto, r.nome_categoria, r.nome_fornecedor, r.valor_preco)

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM gold.dim_produto ORDER BY sk_produto

# COMMAND ----------

# MAGIC %md
# MAGIC ## 3. Dimensão: `dim_tempo`
# MAGIC
# MAGIC Calendário gerado programaticamente de 2023 a 2026.

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS gold.dim_tempo

# COMMAND ----------

from pyspark.sql.functions import expr, date_format

data_inicial = "2023-01-01"
data_final   = "2026-12-31"

num_dias = spark.sql(f"SELECT datediff('{data_final}', '{data_inicial}')").collect()[0][0]

df_calendario = spark.range(0, num_dias + 1) \
    .selectExpr(f"date_add(to_date('{data_inicial}'), CAST(id AS INT)) AS Data")

df_tempo = df_calendario.selectExpr(
    "Data",
    "year(Data) AS Ano",
    "month(Data) AS Mes",
    "(CASE month(Data) \
        WHEN 1  THEN 'JANEIRO'   WHEN 2  THEN 'FEVEREIRO' WHEN 3  THEN 'MARCO' \
        WHEN 4  THEN 'ABRIL'     WHEN 5  THEN 'MAIO'      WHEN 6  THEN 'JUNHO' \
        WHEN 7  THEN 'JULHO'     WHEN 8  THEN 'AGOSTO'    WHEN 9  THEN 'SETEMBRO' \
        WHEN 10 THEN 'OUTUBRO'   WHEN 11 THEN 'NOVEMBRO'  WHEN 12 THEN 'DEZEMBRO' \
    END) AS NomeMes",
    "day(Data) AS Dia",
    "(CASE dayofweek(Data) \
        WHEN 1 THEN 'DOMINGO'       WHEN 2 THEN 'SEGUNDA-FEIRA' \
        WHEN 3 THEN 'TERCA-FEIRA'   WHEN 4 THEN 'QUARTA-FEIRA' \
        WHEN 5 THEN 'QUINTA-FEIRA'  WHEN 6 THEN 'SEXTA-FEIRA' \
        WHEN 7 THEN 'SABADO' \
    END) AS NomeDiaSemana",
    "dayofweek(Data) AS NumeroDiaSemana"
)

df_tempo.display()
df_tempo.write.mode("overwrite").saveAsTable("gold.dim_tempo", format="delta")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 4. Dimensão: `dim_cliente`

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS gold.dim_cliente

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE gold.dim_cliente (
# MAGIC     SK_CLIENTE         BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC     CODIGO_CLIENTE     INT,
# MAGIC     NOME               VARCHAR(100),
# MAGIC     CPF                VARCHAR(11),
# MAGIC     SEXO               CHAR(1),
# MAGIC     DATA_NASCIMENTO    DATE
# MAGIC )
# MAGIC USING DELTA;

# COMMAND ----------

df_cliente.createOrReplaceTempView("cliente")

# COMMAND ----------

# MAGIC %sql
# MAGIC WITH cliente_relacional AS (
# MAGIC     SELECT codigo_cliente,
# MAGIC            nome,
# MAGIC            cpf,
# MAGIC            sexo,
# MAGIC            data_nascimento
# MAGIC       FROM cliente
# MAGIC )
# MAGIC MERGE INTO gold.dim_cliente AS d
# MAGIC USING cliente_relacional AS r
# MAGIC ON r.codigo_cliente = d.codigo_cliente
# MAGIC
# MAGIC WHEN MATCHED AND (r.nome <> d.nome OR r.cpf <> d.cpf OR r.sexo <> d.sexo
# MAGIC                   OR r.data_nascimento <> d.data_nascimento) THEN
# MAGIC     UPDATE SET nome            = r.nome,
# MAGIC                cpf             = r.cpf,
# MAGIC                sexo            = r.sexo,
# MAGIC                data_nascimento = r.data_nascimento
# MAGIC
# MAGIC WHEN NOT MATCHED THEN
# MAGIC     INSERT (codigo_cliente, nome, cpf, sexo, data_nascimento)
# MAGIC     VALUES (r.codigo_cliente, r.nome, r.cpf, r.sexo, r.data_nascimento)

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM gold.dim_cliente ORDER BY sk_cliente

# COMMAND ----------

# MAGIC %md
# MAGIC ## 5. Dimensão: `dim_localidade`

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS gold.dim_localidade

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE gold.dim_localidade (
# MAGIC     SK_LOCALIDADE      BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC     CODIGO_MUNICIPIO   INT,
# MAGIC     NOME_MUNICIPIO     VARCHAR(100),
# MAGIC     NOME_ESTADO        VARCHAR(100),
# MAGIC     NOME_REGIAO        VARCHAR(100)
# MAGIC )
# MAGIC USING DELTA;

# COMMAND ----------

df_municipio.createOrReplaceTempView("municipio")
df_estado.createOrReplaceTempView("estado")
df_regiao.createOrReplaceTempView("regiao")

# COMMAND ----------

# MAGIC %sql
# MAGIC WITH localidade_relacional AS (
# MAGIC     SELECT m.codigo_municipio,
# MAGIC            m.nome_municipio,
# MAGIC            e.nome_estado,
# MAGIC            r.nome_regiao
# MAGIC       FROM municipio m
# MAGIC            INNER JOIN estado e ON m.codigo_estado = e.codigo_estado
# MAGIC            INNER JOIN regiao r ON e.codigo_regiao = r.codigo_regiao
# MAGIC )
# MAGIC MERGE INTO gold.dim_localidade AS d
# MAGIC USING localidade_relacional AS r
# MAGIC ON r.codigo_municipio = d.codigo_municipio
# MAGIC
# MAGIC WHEN MATCHED AND (r.nome_municipio <> d.nome_municipio OR r.nome_estado <> d.nome_estado
# MAGIC                   OR r.nome_regiao <> d.nome_regiao) THEN
# MAGIC     UPDATE SET nome_municipio = r.nome_municipio,
# MAGIC                nome_estado    = r.nome_estado,
# MAGIC                nome_regiao    = r.nome_regiao
# MAGIC
# MAGIC WHEN NOT MATCHED THEN
# MAGIC     INSERT (codigo_municipio, nome_municipio, nome_estado, nome_regiao)
# MAGIC     VALUES (r.codigo_municipio, r.nome_municipio, r.nome_estado, r.nome_regiao)

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM gold.dim_localidade ORDER BY sk_localidade

# COMMAND ----------

# MAGIC %md
# MAGIC ## 6. Tabela Fato: `fato_vendas`
# MAGIC
# MAGIC Grain: um registro por combinação de (data do pedido, produto, cliente, localidade).

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS gold.fato_vendas

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE gold.fato_vendas (
# MAGIC     FK_TEMPO           DATE,
# MAGIC     FK_PRODUTO         INT,
# MAGIC     FK_CLIENTE         INT,
# MAGIC     FK_LOCALIDADE      INT,
# MAGIC     QT_ITENS           INT,
# MAGIC     VL_TOTAL           DOUBLE,
# MAGIC     VL_DESCONTO        DOUBLE
# MAGIC )
# MAGIC USING DELTA;

# COMMAND ----------

df_item_pedido.createOrReplaceTempView("item_pedido")
df_pedido.createOrReplaceTempView("pedido")
df_endereco.createOrReplaceTempView("endereco")

# COMMAND ----------

# MAGIC %sql
# MAGIC WITH pedido_endereco AS (
# MAGIC     SELECT p.codigo_pedido,
# MAGIC            p.codigo_cliente,
# MAGIC            p.data_pedido,
# MAGIC            e.codigo_municipio
# MAGIC       FROM pedido p
# MAGIC            INNER JOIN endereco e ON p.codigo_cliente = e.codigo_cliente
# MAGIC )
# MAGIC INSERT INTO gold.fato_vendas
# MAGIC SELECT dtem.data                               AS FK_TEMPO,
# MAGIC        dp.sk_produto                           AS FK_PRODUTO,
# MAGIC        dc.sk_cliente                           AS FK_CLIENTE,
# MAGIC        dl.sk_localidade                        AS FK_LOCALIDADE,
# MAGIC        SUM(ip.quantidade_quantidade)           AS QT_ITENS,
# MAGIC        SUM(ip.valor_unitario * ip.quantidade_quantidade) AS VL_TOTAL,
# MAGIC        SUM(ip.valor_desconto)                  AS VL_DESCONTO
# MAGIC   FROM item_pedido ip
# MAGIC        INNER JOIN pedido_endereco pe  ON ip.codigo_pedido  = pe.codigo_pedido
# MAGIC        INNER JOIN gold.dim_produto dp ON ip.codigo_produto  = dp.codigo_produto
# MAGIC        INNER JOIN gold.dim_cliente dc ON pe.codigo_cliente  = dc.codigo_cliente
# MAGIC        INNER JOIN gold.dim_localidade dl ON pe.codigo_municipio = dl.codigo_municipio
# MAGIC        INNER JOIN gold.dim_tempo dtem  ON pe.data_pedido    = dtem.data
# MAGIC  GROUP BY dtem.data, dp.sk_produto, dc.sk_cliente, dl.sk_localidade

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM gold.fato_vendas ORDER BY fk_tempo, fk_produto

# COMMAND ----------

# MAGIC %md
# MAGIC ## 7. Consulta analítica de exemplo
# MAGIC
# MAGIC Total de vendas por mês e categoria de produto.

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT t.NomeMes,
# MAGIC        t.Ano,
# MAGIC        p.NOME_CATEGORIA,
# MAGIC        COUNT(1)           AS qtd_pedidos,
# MAGIC        SUM(f.QT_ITENS)    AS total_itens,
# MAGIC        SUM(f.VL_TOTAL)    AS receita_bruta,
# MAGIC        SUM(f.VL_DESCONTO) AS total_descontos,
# MAGIC        SUM(f.VL_TOTAL - f.VL_DESCONTO) AS receita_liquida
# MAGIC   FROM gold.fato_vendas f
# MAGIC        INNER JOIN gold.dim_tempo      t ON f.FK_TEMPO      = t.Data
# MAGIC        INNER JOIN gold.dim_produto    p ON f.FK_PRODUTO     = p.SK_PRODUTO
# MAGIC  GROUP BY t.NomeMes, t.Ano, t.Mes, p.NOME_CATEGORIA
# MAGIC  ORDER BY t.Ano, t.Mes, p.NOME_CATEGORIA
